"""adding reviwer_id field for foreign key

Revision ID: 7e426a7a68a2
Revises: 733605b4d0b1
Create Date: 2023-07-16 15:09:23.723075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e426a7a68a2'
down_revision = '733605b4d0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviwer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviewer_reviwer_id', 'reviewer', ['reviwer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviewer_reviwer_id', type_='foreignkey')
        batch_op.drop_column('reviwer_id')

    # ### end Alembic commands ###
