"""adding reviewers priviledges field on the Rewviwers model

Revision ID: dfa4d1906c04
Revises: 7e426a7a68a2
Create Date: 2023-07-17 01:41:15.005870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa4d1906c04'
down_revision = '7e426a7a68a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_privileges', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewer', schema=None) as batch_op:
        batch_op.drop_column('reviewer_privileges')

    # ### end Alembic commands ###
