"""update users tabel

Revision ID: 709baddc328d
Revises: e68877bdf326
Create Date: 2023-07-11 11:09:59.880916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709baddc328d'
down_revision = 'e68877bdf326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
