"""Add reviewer_privileges to user model. Adding Reviwer model

Revision ID: 733605b4d0b1
Revises: 709baddc328d
Create Date: 2023-07-16 11:12:58.336989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733605b4d0b1'
down_revision = '709baddc328d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviewer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviewer_username'), ['username'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_privileges', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reviewer_privileges')

    with op.batch_alter_table('reviewer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewer_username'))
        batch_op.drop_index(batch_op.f('ix_reviewer_name'))
        batch_op.drop_index(batch_op.f('ix_reviewer_email'))

    op.drop_table('reviewer')
    # ### end Alembic commands ###
